### ISSUE TITLE
bash script not swapping

### ISSUE THREAD

**Issue by Athmajanaji** [techworldthink/Way-to-Coding#13]
https://github.com/techworldthink/Way-to-Coding/blob/befda516cf72457cd36cea9c8ff20346dd30407e/Shell%20Scripting/Task_1/4.1.sh

**Comment by techworldthink** [comment]
> https://github.com/techworldthink/Way-to-Coding/blob/befda516cf72457cd36cea9c8ff20346dd30407e/Shell%20Scripting/Task_1/4.1.sh


INPUT TEXT
.................................................
1001 RAM 97
1025 ARUN 86
1013 RAJU 93


OUTPUT
..................................................
$ cut -d " " -f 1,3 test.txt  > cat  && cut -d " " -f 2 test.txt | paste cat -;
1001 97 RAM
1025 86 ARUN
1013 93 RAJU


CONCLUSION
..................................................

This command swap 2,3 fields and write it to another file "cat". Also u will get output in terminal.
